version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor
            - ./storage:/var/www/storage
        networks:
            - laravel
        ports:
            - "9000:9000"
        depends_on:
            - db

    web:
        image: nginx:1.24
        container_name: laravel-web
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8005:80"
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:15
        container_name: laravel-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: entrevista
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5439:5432"
        networks:
            - laravel


volumes:
    dbdata:

networks:
    laravel: